dist: trusty

before_install:
  - sudo apt-get -qq update

install:
  - sudo pip install ansible

script:
  - "ansible-playbook -i inventory/hosts.example --syntax-check phant.io/install-phant.yml"
  - "sudo ansible-playbook -i inventory/hosts.example phant.io/install-phant.yml"
